/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Date": {                            "en": "Date",                                            "de": "Datum",                                           "ru": "Дата",                                            "pt": "Encontro",                                        "nl": "Datum",                                           "fr": "Rendez-vous amoureux",                            "it": "Data",                                            "es": "Fecha",                                           "pl": "Data"},
    "Description": {                     "en": "Description",                                     "de": "Beschreibung",                                    "ru": "Описание",                                        "pt": "Descrição",                                       "nl": "Beschrijving",                                    "fr": "La description",                                  "it": "Descrizione",                                     "es": "Descripción",                                     "pl": "Opis"},
    "German Holidays Adapter settings": {"en": "German Holidays Adapter settings",                "de": "Deutsche Feiertage Adapter Einstellungen",        "ru": "Настройки Deutsche Feiertage Adapter",            "pt": "Configurações do German Holidays Adapter",        "nl": "Duitse feestdagen Adapterinstellingen",           "fr": "Paramètres de l'adaptateur Vacances allemandes",  "it": "Impostazioni dell'adattatore Vacanze tedesche",   "es": "Configuración del adaptador de vacaciones alemán","pl": "Niemieckie ustawienia adapterów świątecznych"},
    "Holidays": {                        "en": "Holidays",                                        "de": "Feiertage",                                       "ru": "Праздники",                                       "pt": "Feriados",                                        "nl": "Vakantie",                                        "fr": "Vacances",                                        "it": "Vacanze",                                         "es": "Vacaciones",                                      "pl": "Wakacje"},
    "Select": {                          "en": "Select",                                          "de": "Auswahl",                                         "ru": "Выбрать",                                         "pt": "Selecione",                                       "nl": "kiezen",                                          "fr": "Sélectionner",                                    "it": "Selezionare",                                     "es": "Seleccionar",                                     "pl": "Wybierz"},
    "Select holidays": {                 "en": "Select holidays",                                 "de": "Feiertage auswählen",                             "ru": "Выбрать праздники",                               "pt": "Selecione férias",                                "nl": "Selecteer feestdagen",                            "fr": "Sélectionnez les vacances",                       "it": "Seleziona le vacanze",                            "es": "Seleccione vacaciones",                           "pl": "Wybierz święta"},
    "calendrical holiday": {             "en": "calendrical holiday",                             "de": "kalendarischer Feiertag",                         "ru": "календарный праздник",                            "pt": "feriado calendrical",                             "nl": "kalendervakantie",                                "fr": "vacances calendriques",                           "it": "vacanza calendaria",                              "es": "vacaciones calendáricas",                         "pl": "wakacje kalendarzowe"},
    "political holiday": {               "en": "political holiday",                               "de": "politischer Feiertag",                            "ru": "политический праздник",                           "pt": "feriado político",                                "nl": "politieke feestdag",                              "fr": "vacances politiques",                             "it": "vacanza politica",                                "es": "fiesta política",                                 "pl": "święto polityczne"},
    "religous holiday": {                "en": "religous holiday",                                "de": "kirchlicher Feiertag",                            "ru": "религиозный праздник",                            "pt": "feriado religioso",                               "nl": "religieuze vakantie",                             "fr": "fête religieuse",                                 "it": "feste religiose",                                 "es": "vacaciones religiosas",                           "pl": "święto religijne"},
};
