/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Fecha": {                                       "en": "Date",                                            "de": "Datum",                                           "ru": "Дата",                                            "pt": "Encontro",                                        "nl": "Datum",                                           "fr": "Rendez-vous amoureux",                            "it": "Data",                                            "es": "Date",                                            "pl": "Data"},
    "Descripción": {                                 "en": "Description",                                     "de": "Beschreibung",                                    "ru": "Описание",                                        "pt": "Descrição",                                       "nl": "Beschrijving",                                    "fr": "La description",                                  "it": "Descrizione",                                     "es": "Description",                                     "pl": "Opis"},
    "Configuración del adaptador de vacaciones alemán": {"en": "German Holidays Adapter settings",                "de": "Deutsche Feiertage Adapter Einstellungen",        "ru": "Настройки Deutsche Feiertage Adapter",            "pt": "Configurações do German Holidays Adapter",        "nl": "Duitse feestdagen Adapterinstellingen",           "fr": "Paramètres de l'adaptateur Vacances allemandes",  "it": "Impostazioni dell'adattatore Vacanze tedesche",   "es": "German Holidays Adapter settings",                "pl": "Niemieckie ustawienia adapterów świątecznych"},
    "Vacaciones": {                                  "en": "Holidays",                                        "de": "Feiertage",                                       "ru": "Праздники",                                       "pt": "Feriados",                                        "nl": "Vakantie",                                        "fr": "Vacances",                                        "it": "Vacanze",                                         "es": "Holidays",                                        "pl": "Wakacje"},
    "Seleccionar": {                                 "en": "Select",                                          "de": "Auswahl",                                         "ru": "Выбрать",                                         "pt": "Selecione",                                       "nl": "kiezen",                                          "fr": "Sélectionner",                                    "it": "Selezionare",                                     "es": "Select",                                          "pl": "Wybierz"},
    "Seleccione vacaciones": {                       "en": "Select holidays",                                 "de": "Feiertage auswählen",                             "ru": "Выбрать праздники",                               "pt": "Selecione férias",                                "nl": "Selecteer feestdagen",                            "fr": "Sélectionnez les vacances",                       "it": "Seleziona le vacanze",                            "es": "Select holidays",                                 "pl": "Wybierz święta"},
    "vacaciones calendáricas": {                     "en": "calendrical holiday",                             "de": "kalendarischer Feiertag",                         "ru": "календарный праздник",                            "pt": "feriado calendrical",                             "nl": "kalendervakantie",                                "fr": "vacances calendriques",                           "it": "vacanza calendaria",                              "es": "calendrical holiday",                             "pl": "wakacje kalendarzowe"},
    "fiesta política": {                             "en": "political holiday",                               "de": "politischer Feiertag",                            "ru": "политический праздник",                           "pt": "feriado político",                                "nl": "politieke feestdag",                              "fr": "vacances politiques",                             "it": "vacanza politica",                                "es": "political holiday",                               "pl": "święto polityczne"},
    "vacaciones religiosas": {                       "en": "religous holiday",                                "de": "kirchlicher Feiertag",                            "ru": "религиозный праздник",                            "pt": "feriado religioso",                               "nl": "religieuze vakantie",                             "fr": "fête religieuse",                                 "it": "feste religiose",                                 "es": "religous holiday",                                "pl": "święto religijne"},
};